---
title: "TidyTuesday_1"
author: "Kate Seeger"
date: "9/7/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidytuesdayR)
library(ggplot2)
library(dplyr)
library(tidyverse)
library(plotly)
library(ggthemes)

tuesdata <- tidytuesdayR::tt_load('2021-09-07')
tuesdata <- tidytuesdayR::tt_load(2021, week = 37)

results <- tuesdata$results

races <- tuesdata$races
driver_standings <- tuesdata$driver_standings
drivers <- tuesdata$drivers


```


```{r}
driver_results_df <- driver_standings %>% 
  left_join(races, by = "raceId") %>% 
  rename(driver_url = url) %>% 
  left_join(drivers, by = "driverId")
 

```

```{r}

png("tidytues1.png")

driver_results_df %>%
  filter(wins > 0) %>%
  filter(year >=1975,
         nationality == "German" | nationality == "British") %>%
  group_by(nationality, year) %>%
  summarize(sumwins = sum(wins)) %>%
  ungroup() %>%
  ggplot(aes(x = year, y = sumwins, color = nationality)) +
  geom_step() + 
  theme_grey() + 
  labs(title = "Comparing Britain and Germany Total Formula 1 Wins per Year ",  
       x = "",
       y= "", 
       color = "Nationality") 

dev.off()
```

